config/routes.rb
Rails.application.routes.draw do
  root :to => redirect("/users/sign_in")

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords", :confirmations => "users/confirmations"}

  get 'subscribers/pmu' => 'subscribers#pmu', as: :pmu_subscribers
  get 'subscribers/loto_bonheur' => 'subscribers#loto_bonheur', as: :loto_bonheur_subscribers
  get 'subscribers/load_list' => 'subscribers#load_list', as: :subscribers_load_list
  post 'subscribers/load_excel_list' => 'subscribers#load_excel_list', as: :subscribers_load_excel_list

  get 'message' => 'messages#new', as: :message
  post 'message/send' => 'messages#send_message', as: :send_message
  get 'message/send' => 'messages#new'

  get 'transactions' => 'transactions#list', as: :transactions
  get "transactions/numbers_list/:transaction_id" => 'transactions#numbers_list', as: :transaction_numbers_list
  get "transactions/sent_numbers_list/:transaction_id" => 'transactions#sent_numbers_list', as: :transaction_sent_numbers_list
  get "transactions/failed_numbers_list/:transaction_id" => 'transactions#failed_numbers_list', as: :transaction_failed_numbers_list

  get 'message_logs/:transaction_id' => 'message_logs#list', as: :message_logs

  get 'search' => 'search#index', as: :search
  post 'search/perform' => 'search#perform', as: :perform_search
  get 'search/perform' => 'search#index'

  get '/9a9a03436c6aa13773a9d695beeaa8bc/sms_counter' => 'sms_counters#index', as: :sms_counter
  post 'sms_counter/update' => 'sms_counters#update', as: :update_sms_counter

  get "/customer/new" => "customers#new", as: :new_customer
  post "/customer/create" => "customers#create", as: :create_customer
  get "/customer/create" => "customers#new"
  get "/customers/list" => "customers#list", as: :list_customers
  get "/customer/disable/:customer_id" => "customers#disable", as: :disable_customer
  get "/customer/enable/:customer_id" => "customers#enable", as: :enable_customer
  get "/customer/edit/:customer_id" => "customers#edit", as: :edit_customer
  post "/customer/update" => "customers#update", as: :update_customer
  get "/customer/update" => "customers#list"

  get '/ad7e2b2a24677/b19e8e47/api/message/:login/:password/:service_id/:sender/:msisdn/:message' => 'messages#filter_api_send_message', :constraints => {:message => /[^\/]+/}
  get "/customer/sign_in" => "customers#new_session", as: :customer_login
  delete "/customer/sign_out" => "customers#delete_session", as: :customer_sign_out
  post "/customer/session/create" => "customers#create_session", as: :create_customer_session
  get 'customer/transactions' => 'customer_transactions#list', as: :customer_transactions
  get 'customer/message_logs/:transaction_id' => 'customer_message_logs#list', as: :customer_message_logs
  get 'customer/message_logs/export/:transaction_id' => 'customer_message_logs#export', as: :export_customer_message_logs
  get '/ashye5ea24677/b19e8e47/api/message/:login/:password/:service_id/:begin_date/:end_date' => 'message_logs#api_search'
  get '/ashye5ea24677/b19e8e47/api/message/:login/:password/:service_id/:begin_date/:end_date/:msisdn' => 'message_logs#api_search'

  get '*rogue_url', :to => 'errors#routing'
  post '*rogue_url', :to => 'errors#routing'
end

app/controllers/customer_transactions_controller.rb
class CustomerTransactionsController < ApplicationController
  layout "customer"

  def list
    @transactions_active = "active"
    @transactions = Customer.find_by_id(session[:customer]).sms_transactions.order("created_at DESC")
    @transactions_count = @transactions.count
    @transactions = @transactions.page(params[:page])
  end
end

app/helpers/customer_transactions_helper.rb
module CustomerTransactionsHelper
end

app/views/customer_transactions/shared/_sub_menu.html.erb
<div class="statsRow">
  <div class="wrapper">
	<div class="controlB">
  	<ul>
    	<li><a href="<%= customer_transactions_path %>" title=""><img src="<%= asset_path 'icons/control/32/archives.png' %>" alt=""><span>Liste des transactions</span></a></li>
      </ul>
      <div class="clear"></div>
    </div>
  </div>
</div>

app/views/customer_transactions/shared/_transactions_list.html.erb
<thead>
  <tr>
    <td>Profil</td>
    <td>Service</td>
    <td>Emetteur</td>
    <td>Date d'envoi</td>
    <!--<td>Date de fin</td>-->
    <td>Nombre total de messages</td>
    <td>Nombre de messages envoyés</td>
    <td>Nombre de messages échoués</td>
  </tr>
</thead>

<tbody>
  <% unless @transactions.blank? %>
    <% @transactions.each do |transaction| %>
      <tr>
        <% status = (transaction.ended_at.blank? ? 'taskD' : 'taskPr') %>
        <td class = "<%= status %>">
          <%= link_to transaction.profile.name, customer_message_logs_path(transaction.id) %>
        </td>
        <td>
          <%= transaction.service_id  rescue nil %>
          <%#= transaction.sender_service %>
        </td>
        <td>
          <%= transaction.sender_service rescue nil %>
          <%#= transaction.sender_service %>
        </td>
        <td>
          <%= (transaction.started_at.strftime("%d-%m-%Y") rescue "") + " - " + (transaction.started_at.strftime("%Hh %Mmn") rescue "") %>
        </td>
        <!--<td>
          <%= (transaction.ended_at.strftime("%d-%m-%Y") rescue "") + " - " + (transaction.ended_at.strftime("%Hh %Mmn") rescue "") %>
        </td>-->
        <td>
          <%= transaction.number_of_messages %>
        </td>
        <td>
          <%= transaction.send_messages %>
        </td>
        <td>
          <%= transaction.failed_messages %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>