config/routes.rb
Rails.application.routes.draw do
  root :to => redirect("/users/sign_in")

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords", :confirmations => "users/confirmations"}

  get 'subscribers/pmu' => 'subscribers#pmu', as: :pmu_subscribers
  get 'subscribers/loto_bonheur' => 'subscribers#loto_bonheur', as: :loto_bonheur_subscribers
  get 'subscribers/load_list' => 'subscribers#load_list', as: :subscribers_load_list
  post 'subscribers/load_excel_list' => 'subscribers#load_excel_list', as: :subscribers_load_excel_list

  get 'message' => 'messages#new', as: :message
  post 'message/send' => 'messages#send_message', as: :send_message
  get 'message/send' => 'messages#new'

  get 'transactions' => 'transactions#list', as: :transactions
  get "transactions/numbers_list/:transaction_id" => 'transactions#numbers_list', as: :transaction_numbers_list
  get "transactions/sent_numbers_list/:transaction_id" => 'transactions#sent_numbers_list', as: :transaction_sent_numbers_list
  get "transactions/failed_numbers_list/:transaction_id" => 'transactions#failed_numbers_list', as: :transaction_failed_numbers_list

  get 'message_logs/:transaction_id' => 'message_logs#list', as: :message_logs

  get 'search' => 'search#index', as: :search
  post 'search/perform' => 'search#perform', as: :perform_search
  get 'search/perform' => 'search#index'

  get '/9a9a03436c6aa13773a9d695beeaa8bc/sms_counter' => 'sms_counters#index', as: :sms_counter
  post 'sms_counter/update' => 'sms_counters#update', as: :update_sms_counter

  get "/customer/new" => "customers#new", as: :new_customer
  post "/customer/create" => "customers#create", as: :create_customer
  get "/customer/create" => "customers#new"
  get "/customers/list" => "customers#list", as: :list_customers
  get "/customer/disable/:customer_id" => "customers#disable", as: :disable_customer
  get "/customer/enable/:customer_id" => "customers#enable", as: :enable_customer
  get "/customer/edit/:customer_id" => "customers#edit", as: :edit_customer
  post "/customer/update" => "customers#update", as: :update_customer
  get "/customer/update" => "customers#list"

  get '/ad7e2b2a24677/b19e8e47/api/message/:login/:password/:service_id/:sender/:msisdn/:message' => 'messages#filter_api_send_message', :constraints => {:message => /[^\/]+/}
  get "/customer/sign_in" => "customers#new_session", as: :customer_login
  delete "/customer/sign_out" => "customers#delete_session", as: :customer_sign_out
  post "/customer/session/create" => "customers#create_session", as: :create_customer_session
  get 'customer/transactions' => 'customer_transactions#list', as: :customer_transactions
  get 'customer/message_logs/:transaction_id' => 'customer_message_logs#list', as: :customer_message_logs
  get 'customer/message_logs/export/:transaction_id' => 'customer_message_logs#export', as: :export_customer_message_logs
  get '/ashye5ea24677/b19e8e47/api/message/:login/:password/:service_id/:begin_date/:end_date' => 'message_logs#api_search'
  get '/ashye5ea24677/b19e8e47/api/message/:login/:password/:service_id/:begin_date/:end_date/:msisdn' => 'message_logs#api_search'

  get '*rogue_url', :to => 'errors#routing'
  post '*rogue_url', :to => 'errors#routing'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  #prepend_before_filter :authenticate_user!
  require 'rubygems'
  require 'write_xlsx'

  layout "administrator"

  def list
    @transactions_active = "active"
    @transactions = SmsTransaction.all.order("created_at DESC")
    @transactions_count = @transactions.count
    @transactions = @transactions.page(params[:page])
  end

  def numbers_list
    transaction_id = params[:transaction_id]
    numbers = MessageLog.where("sms_transaction_id = ?", transaction_id).select("msisdn")
    export("liste-de-numeros-soumis", numbers)
  end

  def sent_numbers_list
    transaction_id = params[:transaction_id]
    numbers = MessageLog.where("sms_transaction_id = ? AND (status = '1701' OR status = 'PENDING')", transaction_id).select("msisdn")
    export("liste-de-numeros-transmis", numbers)
  end

  def failed_numbers_list
    transaction_id = params[:transaction_id]
    numbers = MessageLog.where("sms_transaction_id = ? AND status <> '1701' AND status <> 'PENDING'", transaction_id).select("msisdn")
    export("liste-de-numeros-non-transmis", numbers)
  end

  def export(title, numbers)
    File.delete("#{Rails.root}/public/#{title}.xlsx") if File.exist?("#{Rails.root}/public/#{title}.xlsx")
    workbook = WriteXLSX.new("#{Rails.root}/public/#{title}.xlsx")
    worksheet = workbook.add_worksheet
    i = 1
    numbers.each do |number|
      worksheet.write("A#{i}", number.msisdn)
      i+=1
    end
    workbook.close

    send_file(
      "#{Rails.root}/public/#{title}.xlsx",
      filename: "#{title}.xlsx",
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    )
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/shared/_sub_menu.html.erb
<div class="statsRow">
  <div class="wrapper">
	<div class="controlB">
  	<ul>
    	<li><a href="<%= transactions_path %>" title=""><img src="<%= asset_path 'icons/control/32/archives.png' %>" alt=""><span>Liste des transactions</span></a></li>
      </ul>
      <div class="clear"></div>
    </div>
  </div>
</div>

app/views/transactions/shared/_transactions_list.html.erb
<thead>
  <tr>
    <td>Service</td>
    <td>Profil</td>
    <td>Date de début</td>
    <td>Date de fin</td>
    <td>Nombre total de messages</td>
    <td>Nombre de messages envoyés</td>
    <td>Nombre de messages échoués</td>
    <td>Exporter</td>
  </tr>
</thead>

<tbody>
  <% unless @transactions.blank? %>
    <% @transactions.each do |transaction| %>
      <tr>
        <% status = (transaction.ended_at.blank? ? 'taskD' : 'taskPr') %>
        <td class = "<%= status %>">
          <% sender = (transaction.customer.label rescue "Administrateur") %>
          <%= link_to sender, message_logs_path(transaction.id) %>
        </td>
        <td>
          <%= link_to transaction.profile.name, message_logs_path(transaction.id) %>
        </td>
        <td>
          <%= (transaction.started_at.strftime("%d-%m-%Y") rescue "") + " - " + (transaction.started_at.strftime("%Hh %Mmn") rescue "") %>
        </td>
        <td>
          <%= (transaction.ended_at.strftime("%d-%m-%Y") rescue "") + " - " + (transaction.ended_at.strftime("%Hh %Mmn") rescue "") %>
        </td>
        <td>
          <%= transaction.number_of_messages %>
        </td>
        <td>
          <%= transaction.send_messages %>
        </td>
        <td>
          <%= transaction.failed_messages %>
        </td>
        <td>
          <% if (transaction.number_of_messages || 0) > 0 %>
            <a href="<%= transaction_numbers_list_path(transaction.id) %>" title = "liste des numéros à transmettre"><img src="<%= asset_path 'icons/color/report-paper.png' %>" alt="liste des numéros à transmettre"></a> &nbsp;
          <% end %>
          <% if (transaction.send_messages || 0) > 0 %>
            <a href="<%= transaction_sent_numbers_list_path(transaction.id) %>"><img src="<%= asset_path 'icons/color/tick.png' %>" alt="liste des numéros transmis"></a> &nbsp;
          <% end %>
          <% if (transaction.failed_messages || 0) > 0 %>
            <a href="<%= transaction_failed_numbers_list_path(transaction.id) %>"><img src="<%= asset_path 'icons/color/minus-circle.png' %>" alt="liste des numéros non transmis"></a>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>