config/routes.rb
Rails.application.routes.draw do
  root :to => redirect("/users/sign_in")

  devise_for :users, :controllers => {:registrations => "users/registrations", :sessions => "users/sessions", :passwords => "users/passwords", :confirmations => "users/confirmations"}

  get 'subscribers/pmu' => 'subscribers#pmu', as: :pmu_subscribers
  get 'subscribers/loto_bonheur' => 'subscribers#loto_bonheur', as: :loto_bonheur_subscribers
  get 'subscribers/load_list' => 'subscribers#load_list', as: :subscribers_load_list
  post 'subscribers/load_excel_list' => 'subscribers#load_excel_list', as: :subscribers_load_excel_list

  get 'message' => 'messages#new', as: :message
  post 'message/send' => 'messages#send_message', as: :send_message
  get 'message/send' => 'messages#new'

  get 'transactions' => 'transactions#list', as: :transactions
  get "transactions/numbers_list/:transaction_id" => 'transactions#numbers_list', as: :transaction_numbers_list
  get "transactions/sent_numbers_list/:transaction_id" => 'transactions#sent_numbers_list', as: :transaction_sent_numbers_list
  get "transactions/failed_numbers_list/:transaction_id" => 'transactions#failed_numbers_list', as: :transaction_failed_numbers_list

  get 'message_logs/:transaction_id' => 'message_logs#list', as: :message_logs

  get 'search' => 'search#index', as: :search
  post 'search/perform' => 'search#perform', as: :perform_search
  get 'search/perform' => 'search#index'

  get '/9a9a03436c6aa13773a9d695beeaa8bc/sms_counter' => 'sms_counters#index', as: :sms_counter
  post 'sms_counter/update' => 'sms_counters#update', as: :update_sms_counter

  get "/customer/new" => "customers#new", as: :new_customer
  post "/customer/create" => "customers#create", as: :create_customer
  get "/customer/create" => "customers#new"
  get "/customers/list" => "customers#list", as: :list_customers
  get "/customer/disable/:customer_id" => "customers#disable", as: :disable_customer
  get "/customer/enable/:customer_id" => "customers#enable", as: :enable_customer
  get "/customer/edit/:customer_id" => "customers#edit", as: :edit_customer
  post "/customer/update" => "customers#update", as: :update_customer
  get "/customer/update" => "customers#list"

  get '/ad7e2b2a24677/b19e8e47/api/message/:login/:password/:service_id/:sender/:msisdn/:message' => 'messages#filter_api_send_message', :constraints => {:message => /[^\/]+/}
  get "/customer/sign_in" => "customers#new_session", as: :customer_login
  delete "/customer/sign_out" => "customers#delete_session", as: :customer_sign_out
  post "/customer/session/create" => "customers#create_session", as: :create_customer_session
  get 'customer/transactions' => 'customer_transactions#list', as: :customer_transactions
  get 'customer/message_logs/:transaction_id' => 'customer_message_logs#list', as: :customer_message_logs
  get 'customer/message_logs/export/:transaction_id' => 'customer_message_logs#export', as: :export_customer_message_logs
  get '/ashye5ea24677/b19e8e47/api/message/:login/:password/:service_id/:begin_date/:end_date' => 'message_logs#api_search'
  get '/ashye5ea24677/b19e8e47/api/message/:login/:password/:service_id/:begin_date/:end_date/:msisdn' => 'message_logs#api_search'

  get '*rogue_url', :to => 'errors#routing'
  post '*rogue_url', :to => 'errors#routing'
end

app/controllers/customer_message_logs_controller.rb
class CustomerMessageLogsController < ApplicationController
  layout "customer"

  def list
    @transactions_active = "active"
    @transaction = SmsTransaction.find_by_id(params[:transaction_id])
    if @transaction.blank?
      render file: "#{Rails.root}/public/404.html", status: 404, layout: false
    else
      @message_logs = @transaction.message_logs
      @message_logs_count = @message_logs.count
      @message_logs = @message_logs.page(params[:page])
    end
  end

  def export
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet
    sheet1.name = 'export'
    @transaction = SmsTransaction.find_by_id(params[:transaction_id])
    if @transaction.blank?
      render file: "#{Rails.root}/public/404.html", status: 404, layout: false
    else
      @message_logs = @transaction.message_logs
      i = 1
      @message_logs.each do |message_log|
        r = sheet1.row(i)
        r.push message_log.msisdn, message_log.message
        i += 1
      end

      path = Rails.root.to_s + '/public/export.xls'
      book.write path

      send_file(path, filename: "export.xls")
    end
  end
end

app/helpers/customer_message_logs_helper.rb
module CustomerMessageLogsHelper
end

app/views/customer_message_logs/shared/_message_logs_list.html.erb
<thead>
  <tr>
    <td>MSISDN</td>
    <td>Libellé</td>
    <td>Emetteur</td>
    <td>Message</td>
    <td>Date d'envoi</td>
    <td>Statut</td>
    <td>Id du message</td>
  </tr>
</thead>

<tbody>
  <% unless @message_logs.blank? %>
    <% @message_logs.each do |message_log| %>
      <tr>
        <% status = (message_log.status == "1701" ? 'taskPr' : 'taskD') %>
        <td class = "<%= status %>">
          <%= message_log.msisdn %>
        </td>
        <td>
          <%= message_log.customer.label rescue nil %>
        </td>
        <td>
          <%= message_log.customer.sender rescue nil %>
        </td>
        <td>
          <%= message_log.message %>
        </td>
        <td>
          <%= message_log.created_at.strftime("%d-%m-%Y") + " - " + message_log.created_at.strftime("%Hh %Mmn") %>
        </td>
        <td>
          <%= message_log.status %>
        </td>
        <td>
          <%= message_log.message_id %>
        </td>
      </tr>
    <% end %>
  <% end %>
</tbody>

app/views/customer_message_logs/shared/_sub_menu.html.erb
<div class="statsRow">
  <div class="wrapper">
  	<div class="controlB">
    	<ul>
      	<li>
          <a href="<%= customer_transactions_path %>" title=""><img src="<%= asset_path 'icons/control/32/archives.png' %>" alt=""><span>Liste des transactions</span></a>
        </li>
        <% if @message_logs_count > 0 %>
          <li>
            <a href="<%= export_customer_message_logs_path %>" title=""><img src="<%= asset_path 'icons/control/32/database.png' %>" alt=""><span>Exporter les résultats</span></a>
          </li>
        <% end %>
      </ul>
      <div class="clear">
      </div>
    </div>
  </div>
</div>